-- Strategic Directives Engine
-- Stores cross-domain strategic analysis reports generated by the three-phase pipeline

CREATE TABLE IF NOT EXISTS strategic_directives (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Full report (JSON)
  report JSONB NOT NULL,

  -- Denormalized for quick queries
  directive_count INTEGER NOT NULL,
  overall_deal_grade TEXT,
  overall_support_grade TEXT,
  overall_customer_grade TEXT,

  -- Who triggered it
  triggered_by UUID REFERENCES auth.users(id),
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('manual', 'scheduled', 'cli')),

  -- Extended thinking output (stored separately for size)
  thinking_output TEXT,

  -- Data snapshot (what data was analyzed)
  data_snapshot JSONB,

  -- Timing
  phase1_duration_ms INTEGER,
  phase2_duration_ms INTEGER,
  phase3_duration_ms INTEGER,
  total_duration_ms INTEGER,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_strategic_directives_created ON strategic_directives(created_at DESC);
CREATE INDEX idx_strategic_directives_triggered_by ON strategic_directives(triggered_by);

ALTER TABLE strategic_directives ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view strategic_directives"
  ON strategic_directives FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Service role manages strategic_directives"
  ON strategic_directives FOR ALL
  USING (auth.jwt() ->> 'role' = 'service_role');
